import type { LucideIcon } from "lucide-react";
import {
	Archive,
	ArrowDownToLine,
	ArrowLeft,
	ArrowUpFromLine,
	Blend,
	Bookmark,
	Camera,
	Check,
	ChevronDown,
	ChevronLeft,
	ChevronRight,
	ChevronUp,
	Clock,
	Columns3,
	Compass,
	Database,
	Droplet,
	Ellipsis,
	ExternalLink,
	Eye,
	FileDown,
	FileUp,
	Folder,
	FolderOpen,
	FolderPlus,
	FolderSymlink,
	GlassWater,
	Globe,
	GripVertical,
	Hourglass,
	Image,
	Import,
	Info,
	LayoutGrid,
	Link,
	ListTree,
	Loader,
	Moon,
	Palette,
	PanelTop,
	Pencil,
	Plus,
	RectangleHorizontal,
	RectangleVertical,
	Scan,
	Search,
	Settings,
	SlidersHorizontal,
	Sparkles,
	Square,
	SquareCheck,
	SunMedium,
	SunMoon,
	Timer,
	Trash2,
	TriangleAlert,
	Type,
	Upload,
	UserRound,
	WandSparkles,
	Wrench,
	X,
} from "lucide-react";

/**
 * Semantic icon name → LucideIcon mapping.
 *
 * NUNCA importar lucide-react diretamente nos componentes da extensão.
 * Use <Icon name="settings" /> de @klice-start/ui/icons/icon.
 */
export const iconMap = {
	plus: Plus,
	search: Search,
	settings: Settings,
	upload: Upload,
	x: X,
	"folder-plus": FolderPlus,
	grip: GripVertical,
	clock: Clock,
	folder: Folder,
	"chevron-right": ChevronRight,
	"chevron-left": ChevronLeft,
	"chevron-down": ChevronDown,
	"chevron-up": ChevronUp,
	check: Check,
	globe: Globe,
	palette: Palette,
	pencil: Pencil,
	sliders: SlidersHorizontal,
	trash: Trash2,
	alert: TriangleAlert,
	loader: Loader,
	ellipsis: Ellipsis,
	info: Info,
	bookmark: Bookmark,
	"arrow-left": ArrowLeft,
	blend: Blend,
	camera: Camera,
	columns: Columns3,
	database: Database,
	"external-link": ExternalLink,
	eye: Eye,
	grid: LayoutGrid,
	image: Image,
	layout: PanelTop,
	sparkles: Sparkles,
	sun: SunMedium,
	timer: Timer,
	text: Type,
	// Aspect-ratio glyphs for the Card shape selector.
	square: Square,
	"rectangle-horizontal": RectangleHorizontal,
	"rectangle-vertical": RectangleVertical,
	// Settings refinements — distinct semantics for flows that previously
	// reused folder/pencil/upload for everything.
	"folder-open": FolderOpen,
	"folder-move": FolderSymlink,
	link: Link,
	tree: ListTree,
	download: ArrowDownToLine,
	"file-import": FileUp,
	"file-export": FileDown,
	import: Import,
	scan: Scan,
	moon: Moon,
	magic: WandSparkles,
	"arrow-up": ArrowUpFromLine,
	// Second refinement pass — one glyph per concept so nothing is reused
	// across unrelated rows (colour, theme mode, glass, backup, engine, you).
	"sun-moon": SunMoon,
	droplet: Droplet,
	"glass-water": GlassWater,
	archive: Archive,
	compass: Compass,
	wrench: Wrench,
	user: UserRound,
	hourglass: Hourglass,
	// Multi-select transport — one glyph for entering selection mode.
	"check-square": SquareCheck,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconMap;
